/* Generated by Yosys 0.57 (git sha1 3aca86049, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module tt_um_Lukasseirl(ui_in, uo_out, uio_in, uio_out, uio_oe, ena, clk, rst_n);
  input [7:0] ui_in;
  wire [7:0] ui_in;
  output [7:0] uo_out;
  wire [7:0] uo_out;
  input [7:0] uio_in;
  wire [7:0] uio_in;
  output [7:0] uio_out;
  wire [7:0] uio_out;
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  input ena;
  wire ena;
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  wire _00_;
  sky130_fd_sc_hd__buf_1 _01_ (
    .A(rst_n),
    .X(_00_)
  );
  sky130_fd_sc_hd__dfxtp_2 _02_ (
    .CLK(clk),
    .D(_00_),
    .Q(uio_out[6])
  );
  sky130_fd_sc_hd__conb_1 _03_ (
    .HI(uio_oe[0])
  );
  sky130_fd_sc_hd__conb_1 _04_ (
    .HI(uio_oe[1])
  );
  sky130_fd_sc_hd__conb_1 _05_ (
    .HI(uio_oe[2])
  );
  sky130_fd_sc_hd__conb_1 _06_ (
    .HI(uio_oe[3])
  );
  sky130_fd_sc_hd__conb_1 _07_ (
    .HI(uio_oe[4])
  );
  sky130_fd_sc_hd__conb_1 _08_ (
    .HI(uio_oe[5])
  );
  sky130_fd_sc_hd__conb_1 _09_ (
    .HI(uio_oe[6])
  );
  sky130_fd_sc_hd__conb_1 _10_ (
    .HI(uio_oe[7])
  );
  sky130_fd_sc_hd__conb_1 _11_ (
    .LO(uio_out[0])
  );
  sky130_fd_sc_hd__conb_1 _12_ (
    .LO(uio_out[7])
  );
  sky130_fd_sc_hd__conb_1 _13_ (
    .LO(uo_out[0])
  );
  sky130_fd_sc_hd__conb_1 _14_ (
    .LO(uo_out[7])
  );
  sky130_fd_sc_hd__buf_2 _15_ (
    .A(uio_out[6]),
    .X(uio_out[1])
  );
  sky130_fd_sc_hd__buf_2 _16_ (
    .A(uio_out[6]),
    .X(uio_out[2])
  );
  sky130_fd_sc_hd__buf_2 _17_ (
    .A(uio_out[6]),
    .X(uio_out[3])
  );
  sky130_fd_sc_hd__buf_2 _18_ (
    .A(uio_out[6]),
    .X(uio_out[4])
  );
  sky130_fd_sc_hd__buf_2 _19_ (
    .A(uio_out[6]),
    .X(uio_out[5])
  );
  sky130_fd_sc_hd__buf_2 _20_ (
    .A(uio_out[6]),
    .X(uo_out[1])
  );
  sky130_fd_sc_hd__buf_2 _21_ (
    .A(uio_out[6]),
    .X(uo_out[2])
  );
  sky130_fd_sc_hd__buf_2 _22_ (
    .A(uio_out[6]),
    .X(uo_out[3])
  );
  sky130_fd_sc_hd__buf_2 _23_ (
    .A(uio_out[6]),
    .X(uo_out[4])
  );
  sky130_fd_sc_hd__buf_2 _24_ (
    .A(uio_out[6]),
    .X(uo_out[5])
  );
  sky130_fd_sc_hd__buf_2 _25_ (
    .A(uio_out[6]),
    .X(uo_out[6])
  );
endmodule
