/* Generated by Yosys 0.57 (git sha1 3aca86049, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module tt_um_Lukasseirl(ui_in, uo_out, uio_in, uio_out, uio_oe, ena, clk, rst_n);
  input [7:0] ui_in;
  wire [7:0] ui_in;
  output [7:0] uo_out;
  wire [7:0] uo_out;
  input [7:0] uio_in;
  wire [7:0] uio_in;
  output [7:0] uio_out;
  wire [7:0] uio_out;
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  input ena;
  wire ena;
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire \scoreboard_inst.bin2dec_inst.bcd_reg[0] ;
  wire \scoreboard_inst.bin2dec_inst.bcd_reg[1] ;
  wire \scoreboard_inst.bin2dec_inst.bcd_reg[2] ;
  wire \scoreboard_inst.bin2dec_inst.bcd_reg[3] ;
  wire \scoreboard_inst.bin2dec_inst.bcd_reg[4] ;
  wire \scoreboard_inst.bin2dec_inst.bcd_reg[5] ;
  wire \scoreboard_inst.bin2dec_inst.bcd_reg[6] ;
  wire \scoreboard_inst.bin2dec_inst.bcd_reg[7] ;
  wire \scoreboard_inst.bin2dec_inst.count[0] ;
  wire \scoreboard_inst.bin2dec_inst.count[1] ;
  wire \scoreboard_inst.bin2dec_inst.count[2] ;
  wire \scoreboard_inst.bin2dec_inst.count[3] ;
  wire \scoreboard_inst.bin2dec_inst.ones_o[0] ;
  wire \scoreboard_inst.bin2dec_inst.ones_o[1] ;
  wire \scoreboard_inst.bin2dec_inst.ones_o[2] ;
  wire \scoreboard_inst.bin2dec_inst.ones_o[3] ;
  wire \scoreboard_inst.bin2dec_inst.state[0] ;
  wire \scoreboard_inst.bin2dec_inst.state[1] ;
  wire \scoreboard_inst.bin2dec_inst.state[2] ;
  wire \scoreboard_inst.bin2dec_inst.state[3] ;
  wire \scoreboard_inst.bin2dec_inst.tens_o[0] ;
  wire \scoreboard_inst.bin2dec_inst.tens_o[1] ;
  wire \scoreboard_inst.bin2dec_inst.tens_o[2] ;
  wire \scoreboard_inst.bin2dec_inst.tens_o[3] ;
  sky130_fd_sc_hd__inv_2 _118_ (
    .A(\scoreboard_inst.bin2dec_inst.bcd_reg[3] ),
    .Y(_092_)
  );
  sky130_fd_sc_hd__inv_2 _119_ (
    .A(\scoreboard_inst.bin2dec_inst.bcd_reg[1] ),
    .Y(_093_)
  );
  sky130_fd_sc_hd__inv_2 _120_ (
    .A(\scoreboard_inst.bin2dec_inst.ones_o[2] ),
    .Y(_094_)
  );
  sky130_fd_sc_hd__inv_2 _121_ (
    .A(\scoreboard_inst.bin2dec_inst.ones_o[1] ),
    .Y(_095_)
  );
  sky130_fd_sc_hd__inv_2 _122_ (
    .A(\scoreboard_inst.bin2dec_inst.ones_o[0] ),
    .Y(_096_)
  );
  sky130_fd_sc_hd__inv_2 _123_ (
    .A(\scoreboard_inst.bin2dec_inst.bcd_reg[7] ),
    .Y(_097_)
  );
  sky130_fd_sc_hd__inv_2 _124_ (
    .A(\scoreboard_inst.bin2dec_inst.tens_o[2] ),
    .Y(_098_)
  );
  sky130_fd_sc_hd__inv_2 _125_ (
    .A(\scoreboard_inst.bin2dec_inst.tens_o[1] ),
    .Y(_099_)
  );
  sky130_fd_sc_hd__inv_2 _126_ (
    .A(\scoreboard_inst.bin2dec_inst.bcd_reg[5] ),
    .Y(_100_)
  );
  sky130_fd_sc_hd__inv_2 _127_ (
    .A(\scoreboard_inst.bin2dec_inst.tens_o[0] ),
    .Y(_101_)
  );
  sky130_fd_sc_hd__inv_2 _128_ (
    .A(\scoreboard_inst.bin2dec_inst.bcd_reg[4] ),
    .Y(_102_)
  );
  sky130_fd_sc_hd__inv_2 _129_ (
    .A(\scoreboard_inst.bin2dec_inst.state[2] ),
    .Y(_103_)
  );
  sky130_fd_sc_hd__inv_2 _130_ (
    .A(\scoreboard_inst.bin2dec_inst.state[0] ),
    .Y(_104_)
  );
  sky130_fd_sc_hd__inv_2 _131_ (
    .A(\scoreboard_inst.bin2dec_inst.state[1] ),
    .Y(_105_)
  );
  sky130_fd_sc_hd__and4bb_2 _132_ (
    .A_N(\scoreboard_inst.bin2dec_inst.count[3] ),
    .B_N(\scoreboard_inst.bin2dec_inst.count[0] ),
    .C(\scoreboard_inst.bin2dec_inst.count[1] ),
    .D(\scoreboard_inst.bin2dec_inst.count[2] ),
    .X(_106_)
  );
  sky130_fd_sc_hd__nor2_2 _133_ (
    .A(_103_),
    .B(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__o21a_2 _134_ (
    .A1(\scoreboard_inst.bin2dec_inst.state[0] ),
    .A2(_107_),
    .B1(rst_n),
    .X(_003_)
  );
  sky130_fd_sc_hd__nand2b_2 _135_ (
    .A_N(\scoreboard_inst.bin2dec_inst.state[3] ),
    .B(rst_n),
    .Y(_002_)
  );
  sky130_fd_sc_hd__and2_2 _136_ (
    .A(rst_n),
    .B(\scoreboard_inst.bin2dec_inst.state[1] ),
    .X(_000_)
  );
  sky130_fd_sc_hd__and3_2 _137_ (
    .A(rst_n),
    .B(\scoreboard_inst.bin2dec_inst.state[2] ),
    .C(_106_),
    .X(_001_)
  );
  sky130_fd_sc_hd__nand2_2 _138_ (
    .A(\scoreboard_inst.bin2dec_inst.tens_o[1] ),
    .B(\scoreboard_inst.bin2dec_inst.tens_o[0] ),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nand2_2 _139_ (
    .A(\scoreboard_inst.bin2dec_inst.tens_o[2] ),
    .B(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__o21ai_2 _140_ (
    .A1(\scoreboard_inst.bin2dec_inst.tens_o[2] ),
    .A2(_099_),
    .B1(_109_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__o21a_2 _141_ (
    .A1(\scoreboard_inst.bin2dec_inst.tens_o[3] ),
    .A2(_110_),
    .B1(rst_n),
    .X(_004_)
  );
  sky130_fd_sc_hd__o21ai_2 _142_ (
    .A1(\scoreboard_inst.bin2dec_inst.tens_o[2] ),
    .A2(\scoreboard_inst.bin2dec_inst.tens_o[1] ),
    .B1(\scoreboard_inst.bin2dec_inst.tens_o[3] ),
    .Y(_111_)
  );
  sky130_fd_sc_hd__and2_2 _143_ (
    .A(rst_n),
    .B(_111_),
    .X(_112_)
  );
  sky130_fd_sc_hd__nor2_2 _144_ (
    .A(\scoreboard_inst.bin2dec_inst.tens_o[1] ),
    .B(\scoreboard_inst.bin2dec_inst.tens_o[0] ),
    .Y(_113_)
  );
  sky130_fd_sc_hd__a211o_2 _145_ (
    .A1(\scoreboard_inst.bin2dec_inst.tens_o[2] ),
    .A2(_108_),
    .B1(_113_),
    .C1(\scoreboard_inst.bin2dec_inst.tens_o[3] ),
    .X(_114_)
  );
  sky130_fd_sc_hd__and2_2 _146_ (
    .A(_112_),
    .B(_114_),
    .X(_005_)
  );
  sky130_fd_sc_hd__o211a_2 _147_ (
    .A1(_098_),
    .A2(\scoreboard_inst.bin2dec_inst.tens_o[1] ),
    .B1(_101_),
    .C1(_112_),
    .X(_006_)
  );
  sky130_fd_sc_hd__nor2_2 _148_ (
    .A(_098_),
    .B(_113_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nor2_2 _149_ (
    .A(_109_),
    .B(_113_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__a21oi_2 _150_ (
    .A1(_099_),
    .A2(\scoreboard_inst.bin2dec_inst.tens_o[0] ),
    .B1(\scoreboard_inst.bin2dec_inst.tens_o[2] ),
    .Y(_117_)
  );
  sky130_fd_sc_hd__o31a_2 _151_ (
    .A1(\scoreboard_inst.bin2dec_inst.tens_o[3] ),
    .A2(_116_),
    .A3(_117_),
    .B1(_112_),
    .X(_007_)
  );
  sky130_fd_sc_hd__o31a_2 _152_ (
    .A1(\scoreboard_inst.bin2dec_inst.tens_o[2] ),
    .A2(_099_),
    .A3(\scoreboard_inst.bin2dec_inst.tens_o[0] ),
    .B1(_112_),
    .X(_008_)
  );
  sky130_fd_sc_hd__o31a_2 _153_ (
    .A1(\scoreboard_inst.bin2dec_inst.tens_o[3] ),
    .A2(_109_),
    .A3(_113_),
    .B1(_112_),
    .X(_009_)
  );
  sky130_fd_sc_hd__o31a_2 _154_ (
    .A1(\scoreboard_inst.bin2dec_inst.tens_o[3] ),
    .A2(_115_),
    .A3(_117_),
    .B1(_112_),
    .X(_010_)
  );
  sky130_fd_sc_hd__or2_2 _155_ (
    .A(\scoreboard_inst.bin2dec_inst.state[2] ),
    .B(\scoreboard_inst.bin2dec_inst.state[1] ),
    .X(_038_)
  );
  sky130_fd_sc_hd__nor3_2 _156_ (
    .A(\scoreboard_inst.bin2dec_inst.state[2] ),
    .B(\scoreboard_inst.bin2dec_inst.state[0] ),
    .C(\scoreboard_inst.bin2dec_inst.state[1] ),
    .Y(_039_)
  );
  sky130_fd_sc_hd__o21a_2 _157_ (
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[5] ),
    .A2(\scoreboard_inst.bin2dec_inst.bcd_reg[4] ),
    .B1(\scoreboard_inst.bin2dec_inst.bcd_reg[6] ),
    .X(_040_)
  );
  sky130_fd_sc_hd__o21ai_2 _158_ (
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[5] ),
    .A2(\scoreboard_inst.bin2dec_inst.bcd_reg[4] ),
    .B1(\scoreboard_inst.bin2dec_inst.bcd_reg[6] ),
    .Y(_041_)
  );
  sky130_fd_sc_hd__o32a_2 _159_ (
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[7] ),
    .A2(_105_),
    .A3(_040_),
    .B1(_038_),
    .B2(\scoreboard_inst.bin2dec_inst.state[0] ),
    .X(_042_)
  );
  sky130_fd_sc_hd__a31o_2 _160_ (
    .A1(_097_),
    .A2(\scoreboard_inst.bin2dec_inst.state[1] ),
    .A3(_041_),
    .B1(_039_),
    .X(_043_)
  );
  sky130_fd_sc_hd__a221o_2 _161_ (
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[3] ),
    .A2(\scoreboard_inst.bin2dec_inst.state[2] ),
    .B1(\scoreboard_inst.bin2dec_inst.state[1] ),
    .B2(_102_),
    .C1(_043_),
    .X(_044_)
  );
  sky130_fd_sc_hd__o211a_2 _162_ (
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[4] ),
    .A2(_042_),
    .B1(_044_),
    .C1(rst_n),
    .X(_011_)
  );
  sky130_fd_sc_hd__a21oi_2 _163_ (
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[4] ),
    .A2(_103_),
    .B1(_043_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__a221o_2 _164_ (
    .A1(_100_),
    .A2(\scoreboard_inst.bin2dec_inst.state[1] ),
    .B1(_038_),
    .B2(\scoreboard_inst.bin2dec_inst.bcd_reg[4] ),
    .C1(_043_),
    .X(_046_)
  );
  sky130_fd_sc_hd__o211a_2 _165_ (
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[5] ),
    .A2(_045_),
    .B1(_046_),
    .C1(rst_n),
    .X(_012_)
  );
  sky130_fd_sc_hd__or3_2 _166_ (
    .A(\scoreboard_inst.bin2dec_inst.bcd_reg[6] ),
    .B(\scoreboard_inst.bin2dec_inst.bcd_reg[5] ),
    .C(\scoreboard_inst.bin2dec_inst.bcd_reg[4] ),
    .X(_047_)
  );
  sky130_fd_sc_hd__a32o_2 _167_ (
    .A1(\scoreboard_inst.bin2dec_inst.state[1] ),
    .A2(_041_),
    .A3(_047_),
    .B1(\scoreboard_inst.bin2dec_inst.state[2] ),
    .B2(\scoreboard_inst.bin2dec_inst.bcd_reg[5] ),
    .X(_048_)
  );
  sky130_fd_sc_hd__or2_2 _168_ (
    .A(_043_),
    .B(_048_),
    .X(_049_)
  );
  sky130_fd_sc_hd__o211a_2 _169_ (
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[6] ),
    .A2(_042_),
    .B1(_049_),
    .C1(rst_n),
    .X(_013_)
  );
  sky130_fd_sc_hd__xnor2_2 _170_ (
    .A(_097_),
    .B(_040_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a221o_2 _171_ (
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[6] ),
    .A2(\scoreboard_inst.bin2dec_inst.state[2] ),
    .B1(\scoreboard_inst.bin2dec_inst.state[1] ),
    .B2(_050_),
    .C1(_043_),
    .X(_051_)
  );
  sky130_fd_sc_hd__o211a_2 _172_ (
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[7] ),
    .A2(_042_),
    .B1(_051_),
    .C1(rst_n),
    .X(_014_)
  );
  sky130_fd_sc_hd__nand2_2 _173_ (
    .A(\scoreboard_inst.bin2dec_inst.ones_o[1] ),
    .B(\scoreboard_inst.bin2dec_inst.ones_o[0] ),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_2 _174_ (
    .A(\scoreboard_inst.bin2dec_inst.ones_o[2] ),
    .B(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__o21ai_2 _175_ (
    .A1(\scoreboard_inst.bin2dec_inst.ones_o[2] ),
    .A2(_095_),
    .B1(_053_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__o21a_2 _176_ (
    .A1(\scoreboard_inst.bin2dec_inst.ones_o[3] ),
    .A2(_054_),
    .B1(rst_n),
    .X(_015_)
  );
  sky130_fd_sc_hd__o21ai_2 _177_ (
    .A1(\scoreboard_inst.bin2dec_inst.ones_o[2] ),
    .A2(\scoreboard_inst.bin2dec_inst.ones_o[1] ),
    .B1(\scoreboard_inst.bin2dec_inst.ones_o[3] ),
    .Y(_055_)
  );
  sky130_fd_sc_hd__and2_2 _178_ (
    .A(rst_n),
    .B(_055_),
    .X(_056_)
  );
  sky130_fd_sc_hd__nor2_2 _179_ (
    .A(\scoreboard_inst.bin2dec_inst.ones_o[1] ),
    .B(\scoreboard_inst.bin2dec_inst.ones_o[0] ),
    .Y(_057_)
  );
  sky130_fd_sc_hd__a211o_2 _180_ (
    .A1(\scoreboard_inst.bin2dec_inst.ones_o[2] ),
    .A2(_052_),
    .B1(_057_),
    .C1(\scoreboard_inst.bin2dec_inst.ones_o[3] ),
    .X(_058_)
  );
  sky130_fd_sc_hd__and2_2 _181_ (
    .A(_056_),
    .B(_058_),
    .X(_016_)
  );
  sky130_fd_sc_hd__o211a_2 _182_ (
    .A1(_094_),
    .A2(\scoreboard_inst.bin2dec_inst.ones_o[1] ),
    .B1(_096_),
    .C1(_056_),
    .X(_017_)
  );
  sky130_fd_sc_hd__nor2_2 _183_ (
    .A(_094_),
    .B(_057_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor2_2 _184_ (
    .A(_053_),
    .B(_057_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__a21oi_2 _185_ (
    .A1(_095_),
    .A2(\scoreboard_inst.bin2dec_inst.ones_o[0] ),
    .B1(\scoreboard_inst.bin2dec_inst.ones_o[2] ),
    .Y(_061_)
  );
  sky130_fd_sc_hd__o31a_2 _186_ (
    .A1(\scoreboard_inst.bin2dec_inst.ones_o[3] ),
    .A2(_060_),
    .A3(_061_),
    .B1(_056_),
    .X(_018_)
  );
  sky130_fd_sc_hd__o31a_2 _187_ (
    .A1(\scoreboard_inst.bin2dec_inst.ones_o[2] ),
    .A2(_095_),
    .A3(\scoreboard_inst.bin2dec_inst.ones_o[0] ),
    .B1(_056_),
    .X(_019_)
  );
  sky130_fd_sc_hd__o31a_2 _188_ (
    .A1(\scoreboard_inst.bin2dec_inst.ones_o[3] ),
    .A2(_053_),
    .A3(_057_),
    .B1(_056_),
    .X(_020_)
  );
  sky130_fd_sc_hd__o31a_2 _189_ (
    .A1(\scoreboard_inst.bin2dec_inst.ones_o[3] ),
    .A2(_059_),
    .A3(_061_),
    .B1(_056_),
    .X(_021_)
  );
  sky130_fd_sc_hd__o21ai_2 _190_ (
    .A1(\scoreboard_inst.bin2dec_inst.state[3] ),
    .A2(\scoreboard_inst.bin2dec_inst.tens_o[0] ),
    .B1(rst_n),
    .Y(_062_)
  );
  sky130_fd_sc_hd__a21oi_2 _191_ (
    .A1(\scoreboard_inst.bin2dec_inst.state[3] ),
    .A2(_102_),
    .B1(_062_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__o21ai_2 _192_ (
    .A1(\scoreboard_inst.bin2dec_inst.state[3] ),
    .A2(\scoreboard_inst.bin2dec_inst.tens_o[1] ),
    .B1(rst_n),
    .Y(_063_)
  );
  sky130_fd_sc_hd__a21oi_2 _193_ (
    .A1(\scoreboard_inst.bin2dec_inst.state[3] ),
    .A2(_100_),
    .B1(_063_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _194_ (
    .A0(\scoreboard_inst.bin2dec_inst.tens_o[2] ),
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[6] ),
    .S(\scoreboard_inst.bin2dec_inst.state[3] ),
    .X(_064_)
  );
  sky130_fd_sc_hd__and2_2 _195_ (
    .A(rst_n),
    .B(_064_),
    .X(_024_)
  );
  sky130_fd_sc_hd__o21ai_2 _196_ (
    .A1(\scoreboard_inst.bin2dec_inst.state[3] ),
    .A2(\scoreboard_inst.bin2dec_inst.tens_o[3] ),
    .B1(rst_n),
    .Y(_065_)
  );
  sky130_fd_sc_hd__a21oi_2 _197_ (
    .A1(\scoreboard_inst.bin2dec_inst.state[3] ),
    .A2(_097_),
    .B1(_065_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _198_ (
    .A0(\scoreboard_inst.bin2dec_inst.ones_o[0] ),
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[0] ),
    .S(\scoreboard_inst.bin2dec_inst.state[3] ),
    .X(_066_)
  );
  sky130_fd_sc_hd__and2_2 _199_ (
    .A(rst_n),
    .B(_066_),
    .X(_026_)
  );
  sky130_fd_sc_hd__o21ai_2 _200_ (
    .A1(\scoreboard_inst.bin2dec_inst.state[3] ),
    .A2(\scoreboard_inst.bin2dec_inst.ones_o[1] ),
    .B1(rst_n),
    .Y(_067_)
  );
  sky130_fd_sc_hd__a21oi_2 _201_ (
    .A1(_093_),
    .A2(\scoreboard_inst.bin2dec_inst.state[3] ),
    .B1(_067_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _202_ (
    .A0(\scoreboard_inst.bin2dec_inst.ones_o[2] ),
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[2] ),
    .S(\scoreboard_inst.bin2dec_inst.state[3] ),
    .X(_068_)
  );
  sky130_fd_sc_hd__and2_2 _203_ (
    .A(rst_n),
    .B(_068_),
    .X(_028_)
  );
  sky130_fd_sc_hd__o21ai_2 _204_ (
    .A1(\scoreboard_inst.bin2dec_inst.ones_o[3] ),
    .A2(\scoreboard_inst.bin2dec_inst.state[3] ),
    .B1(rst_n),
    .Y(_069_)
  );
  sky130_fd_sc_hd__a21oi_2 _205_ (
    .A1(_092_),
    .A2(\scoreboard_inst.bin2dec_inst.state[3] ),
    .B1(_069_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _206_ (
    .A0(_104_),
    .A1(_106_),
    .S(\scoreboard_inst.bin2dec_inst.state[2] ),
    .X(_070_)
  );
  sky130_fd_sc_hd__o21ai_2 _207_ (
    .A1(\scoreboard_inst.bin2dec_inst.state[2] ),
    .A2(\scoreboard_inst.bin2dec_inst.state[0] ),
    .B1(\scoreboard_inst.bin2dec_inst.count[0] ),
    .Y(_071_)
  );
  sky130_fd_sc_hd__o211a_2 _208_ (
    .A1(\scoreboard_inst.bin2dec_inst.count[0] ),
    .A2(_107_),
    .B1(_071_),
    .C1(rst_n),
    .X(_030_)
  );
  sky130_fd_sc_hd__nand2_2 _209_ (
    .A(\scoreboard_inst.bin2dec_inst.count[1] ),
    .B(\scoreboard_inst.bin2dec_inst.count[0] ),
    .Y(_072_)
  );
  sky130_fd_sc_hd__a22o_2 _210_ (
    .A1(\scoreboard_inst.bin2dec_inst.count[1] ),
    .A2(_070_),
    .B1(_072_),
    .B2(_107_),
    .X(_073_)
  );
  sky130_fd_sc_hd__o211a_2 _211_ (
    .A1(\scoreboard_inst.bin2dec_inst.count[1] ),
    .A2(\scoreboard_inst.bin2dec_inst.count[0] ),
    .B1(rst_n),
    .C1(_073_),
    .X(_031_)
  );
  sky130_fd_sc_hd__a21oi_2 _212_ (
    .A1(\scoreboard_inst.bin2dec_inst.count[2] ),
    .A2(_104_),
    .B1(\scoreboard_inst.bin2dec_inst.state[2] ),
    .Y(_074_)
  );
  sky130_fd_sc_hd__a21oi_2 _213_ (
    .A1(\scoreboard_inst.bin2dec_inst.count[1] ),
    .A2(\scoreboard_inst.bin2dec_inst.count[0] ),
    .B1(\scoreboard_inst.bin2dec_inst.count[2] ),
    .Y(_075_)
  );
  sky130_fd_sc_hd__and4_2 _214_ (
    .A(\scoreboard_inst.bin2dec_inst.count[2] ),
    .B(\scoreboard_inst.bin2dec_inst.count[1] ),
    .C(\scoreboard_inst.bin2dec_inst.count[0] ),
    .D(\scoreboard_inst.bin2dec_inst.state[2] ),
    .X(_076_)
  );
  sky130_fd_sc_hd__or4b_2 _215_ (
    .A(_074_),
    .B(_075_),
    .C(_076_),
    .D_N(rst_n),
    .X(_077_)
  );
  sky130_fd_sc_hd__inv_2 _216_ (
    .A(_077_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__o221a_2 _217_ (
    .A1(\scoreboard_inst.bin2dec_inst.state[2] ),
    .A2(_104_),
    .B1(_076_),
    .B2(\scoreboard_inst.bin2dec_inst.count[3] ),
    .C1(rst_n),
    .X(_078_)
  );
  sky130_fd_sc_hd__a21boi_2 _218_ (
    .A1(\scoreboard_inst.bin2dec_inst.count[3] ),
    .A2(_076_),
    .B1_N(_078_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__o21a_2 _219_ (
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[1] ),
    .A2(\scoreboard_inst.bin2dec_inst.bcd_reg[0] ),
    .B1(\scoreboard_inst.bin2dec_inst.bcd_reg[2] ),
    .X(_079_)
  );
  sky130_fd_sc_hd__o21ai_2 _220_ (
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[1] ),
    .A2(\scoreboard_inst.bin2dec_inst.bcd_reg[0] ),
    .B1(\scoreboard_inst.bin2dec_inst.bcd_reg[2] ),
    .Y(_080_)
  );
  sky130_fd_sc_hd__o32a_2 _221_ (
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[3] ),
    .A2(_105_),
    .A3(_079_),
    .B1(_038_),
    .B2(\scoreboard_inst.bin2dec_inst.state[0] ),
    .X(_081_)
  );
  sky130_fd_sc_hd__a31o_2 _222_ (
    .A1(_092_),
    .A2(\scoreboard_inst.bin2dec_inst.state[1] ),
    .A3(_080_),
    .B1(_039_),
    .X(_082_)
  );
  sky130_fd_sc_hd__nand2_2 _223_ (
    .A(\scoreboard_inst.bin2dec_inst.bcd_reg[0] ),
    .B(_081_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__a21oi_2 _224_ (
    .A1(_092_),
    .A2(_080_),
    .B1(_105_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__o211a_2 _225_ (
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[0] ),
    .A2(_084_),
    .B1(_083_),
    .C1(rst_n),
    .X(_034_)
  );
  sky130_fd_sc_hd__a21oi_2 _226_ (
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[0] ),
    .A2(_103_),
    .B1(_082_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__a221o_2 _227_ (
    .A1(_093_),
    .A2(\scoreboard_inst.bin2dec_inst.state[1] ),
    .B1(_038_),
    .B2(\scoreboard_inst.bin2dec_inst.bcd_reg[0] ),
    .C1(_082_),
    .X(_086_)
  );
  sky130_fd_sc_hd__o211a_2 _228_ (
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[1] ),
    .A2(_085_),
    .B1(_086_),
    .C1(rst_n),
    .X(_035_)
  );
  sky130_fd_sc_hd__or3_2 _229_ (
    .A(\scoreboard_inst.bin2dec_inst.bcd_reg[2] ),
    .B(\scoreboard_inst.bin2dec_inst.bcd_reg[1] ),
    .C(\scoreboard_inst.bin2dec_inst.bcd_reg[0] ),
    .X(_087_)
  );
  sky130_fd_sc_hd__a32o_2 _230_ (
    .A1(\scoreboard_inst.bin2dec_inst.state[1] ),
    .A2(_080_),
    .A3(_087_),
    .B1(\scoreboard_inst.bin2dec_inst.state[2] ),
    .B2(\scoreboard_inst.bin2dec_inst.bcd_reg[1] ),
    .X(_088_)
  );
  sky130_fd_sc_hd__or2_2 _231_ (
    .A(_082_),
    .B(_088_),
    .X(_089_)
  );
  sky130_fd_sc_hd__o211a_2 _232_ (
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[2] ),
    .A2(_081_),
    .B1(_089_),
    .C1(rst_n),
    .X(_036_)
  );
  sky130_fd_sc_hd__nand2_2 _233_ (
    .A(\scoreboard_inst.bin2dec_inst.bcd_reg[3] ),
    .B(_079_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__a221o_2 _234_ (
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[2] ),
    .A2(\scoreboard_inst.bin2dec_inst.state[2] ),
    .B1(_084_),
    .B2(_090_),
    .C1(_082_),
    .X(_091_)
  );
  sky130_fd_sc_hd__o211a_2 _235_ (
    .A1(\scoreboard_inst.bin2dec_inst.bcd_reg[3] ),
    .A2(_081_),
    .B1(_091_),
    .C1(rst_n),
    .X(_037_)
  );
  sky130_fd_sc_hd__dfxtp_2 _236_ (
    .CLK(clk),
    .D(_004_),
    .Q(uo_out[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _237_ (
    .CLK(clk),
    .D(_005_),
    .Q(uo_out[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _238_ (
    .CLK(clk),
    .D(_006_),
    .Q(uo_out[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _239_ (
    .CLK(clk),
    .D(_007_),
    .Q(uo_out[3])
  );
  sky130_fd_sc_hd__dfxtp_2 _240_ (
    .CLK(clk),
    .D(_008_),
    .Q(uo_out[4])
  );
  sky130_fd_sc_hd__dfxtp_2 _241_ (
    .CLK(clk),
    .D(_009_),
    .Q(uo_out[5])
  );
  sky130_fd_sc_hd__dfxtp_2 _242_ (
    .CLK(clk),
    .D(_010_),
    .Q(uo_out[6])
  );
  sky130_fd_sc_hd__dfxtp_2 _243_ (
    .CLK(clk),
    .D(_002_),
    .Q(\scoreboard_inst.bin2dec_inst.state[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _244_ (
    .CLK(clk),
    .D(_003_),
    .Q(\scoreboard_inst.bin2dec_inst.state[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _245_ (
    .CLK(clk),
    .D(_000_),
    .Q(\scoreboard_inst.bin2dec_inst.state[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _246_ (
    .CLK(clk),
    .D(_001_),
    .Q(\scoreboard_inst.bin2dec_inst.state[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _247_ (
    .CLK(clk),
    .D(_011_),
    .Q(\scoreboard_inst.bin2dec_inst.bcd_reg[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _248_ (
    .CLK(clk),
    .D(_012_),
    .Q(\scoreboard_inst.bin2dec_inst.bcd_reg[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _249_ (
    .CLK(clk),
    .D(_013_),
    .Q(\scoreboard_inst.bin2dec_inst.bcd_reg[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _250_ (
    .CLK(clk),
    .D(_014_),
    .Q(\scoreboard_inst.bin2dec_inst.bcd_reg[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _251_ (
    .CLK(clk),
    .D(_015_),
    .Q(uio_out[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _252_ (
    .CLK(clk),
    .D(_016_),
    .Q(uio_out[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _253_ (
    .CLK(clk),
    .D(_017_),
    .Q(uio_out[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _254_ (
    .CLK(clk),
    .D(_018_),
    .Q(uio_out[3])
  );
  sky130_fd_sc_hd__dfxtp_2 _255_ (
    .CLK(clk),
    .D(_019_),
    .Q(uio_out[4])
  );
  sky130_fd_sc_hd__dfxtp_2 _256_ (
    .CLK(clk),
    .D(_020_),
    .Q(uio_out[5])
  );
  sky130_fd_sc_hd__dfxtp_2 _257_ (
    .CLK(clk),
    .D(_021_),
    .Q(uio_out[6])
  );
  sky130_fd_sc_hd__dfxtp_2 _258_ (
    .CLK(clk),
    .D(_022_),
    .Q(\scoreboard_inst.bin2dec_inst.tens_o[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _259_ (
    .CLK(clk),
    .D(_023_),
    .Q(\scoreboard_inst.bin2dec_inst.tens_o[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _260_ (
    .CLK(clk),
    .D(_024_),
    .Q(\scoreboard_inst.bin2dec_inst.tens_o[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _261_ (
    .CLK(clk),
    .D(_025_),
    .Q(\scoreboard_inst.bin2dec_inst.tens_o[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _262_ (
    .CLK(clk),
    .D(_026_),
    .Q(\scoreboard_inst.bin2dec_inst.ones_o[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _263_ (
    .CLK(clk),
    .D(_027_),
    .Q(\scoreboard_inst.bin2dec_inst.ones_o[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _264_ (
    .CLK(clk),
    .D(_028_),
    .Q(\scoreboard_inst.bin2dec_inst.ones_o[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _265_ (
    .CLK(clk),
    .D(_029_),
    .Q(\scoreboard_inst.bin2dec_inst.ones_o[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _266_ (
    .CLK(clk),
    .D(_030_),
    .Q(\scoreboard_inst.bin2dec_inst.count[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _267_ (
    .CLK(clk),
    .D(_031_),
    .Q(\scoreboard_inst.bin2dec_inst.count[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _268_ (
    .CLK(clk),
    .D(_032_),
    .Q(\scoreboard_inst.bin2dec_inst.count[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _269_ (
    .CLK(clk),
    .D(_033_),
    .Q(\scoreboard_inst.bin2dec_inst.count[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _270_ (
    .CLK(clk),
    .D(_034_),
    .Q(\scoreboard_inst.bin2dec_inst.bcd_reg[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _271_ (
    .CLK(clk),
    .D(_035_),
    .Q(\scoreboard_inst.bin2dec_inst.bcd_reg[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _272_ (
    .CLK(clk),
    .D(_036_),
    .Q(\scoreboard_inst.bin2dec_inst.bcd_reg[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _273_ (
    .CLK(clk),
    .D(_037_),
    .Q(\scoreboard_inst.bin2dec_inst.bcd_reg[3] )
  );
  sky130_fd_sc_hd__conb_1 _274_ (
    .HI(uio_oe[0])
  );
  sky130_fd_sc_hd__conb_1 _275_ (
    .HI(uio_oe[1])
  );
  sky130_fd_sc_hd__conb_1 _276_ (
    .HI(uio_oe[2])
  );
  sky130_fd_sc_hd__conb_1 _277_ (
    .HI(uio_oe[3])
  );
  sky130_fd_sc_hd__conb_1 _278_ (
    .HI(uio_oe[4])
  );
  sky130_fd_sc_hd__conb_1 _279_ (
    .HI(uio_oe[5])
  );
  sky130_fd_sc_hd__conb_1 _280_ (
    .HI(uio_oe[6])
  );
  sky130_fd_sc_hd__conb_1 _281_ (
    .HI(uio_oe[7])
  );
  sky130_fd_sc_hd__conb_1 _282_ (
    .LO(uio_out[7])
  );
  sky130_fd_sc_hd__conb_1 _283_ (
    .LO(uo_out[7])
  );
endmodule
